[project]
name = "winreg_read"
version = "0.1.0"
description = "Read Win Reg Values"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
