[project]
name = "pep514-winreg"
version = "0.1.0"
description = "PEP 514 Sample Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
